name: Semantic Release

inputs: 
  node_version:
    type: string
    default: "20"

runs:
  using: "composite"
  steps:
    - run: install nodejs
      uses: actions/setup-node@v4
      env:
        node-version: ${{ inputs.node_version }}

    - name: install semantic release
      run:
        npm install -g semantic-release@v13 \
        @semantic-release/commit-analyzer@v13 \
        @semantic-release/release-notes-generator@v14 \
        @semantic-release/changelog@v6 \
        @semantic-release/npm@v10 \
        @semantic-release/git@v10 \
        @semantic-release/github@v10 \
        @semantic-release/exec@v6 \
        conventional-changelog-conventionalcommits@v7 \
        semantic-release-major-tag
      shell: bash

    - name: copy standard releaserc config
      run: cp ${{ github.actions_path }}/config/.releaserc .
      shell: bash

    - name: run semantic release and create version
      run: semantic-release
      shell: bash