name: "Terraform Validate"

on:
  workflow_call:
    inputs:
      base_dir:
        type: string
        default: "."
      runs-on:
        type: string
        default: "ubuntu-latest"
      checkout_ref:
        type: string
        default: ""
      terraform_version:
        type: string
        default: ""
      tflint_version:
        type: string
        default: "latest"
      allow_to_fail:
        type: boolean
        default: false

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs: 
  fmt: 
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: ${{ inputs.allow_to_fail  }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive
        working-directory: ${{ inputs.base_dir }}

  validate: 
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: ${{ inputs.allow_to_fail  }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}   
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ inputs.terraform_version }}
      
      - name: Terraform Validate
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: ${{ inputs.base_dir }}

  tflint: 
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: ${{ inputs.allow_to_fail  }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}   
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Setup TFLint
        uses: azu-ets/cse-tflint@v1
        with:
          version: ${{ inputs.tflint_version }}
   
      - name: TFLint
        id: tflint
        run: | 
          if [ -f ${GITHUB_WORKSPACE}/.tflint.hcl ] && [ ! -f .tflint.hcl ] ; then
            cp ${GITHUB_WORKSPACE}/.tflint.hcl .tflint.hcl
          fi
          tflint --init
          tflint -f compact --recursive
        working-directory: ${{ inputs.base_dir }}

  checkov:
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: ${{ inputs.allow_to_fail  }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}   

      - name: Checkov Github Action
        uses: bridgecrewio/checkov-action@v12
        with: 
          quiet: true
          output_format: cli,sarif
          output_file_path: console,results.sarif